const allSongs = {
	modern: [
		{
			link: "Memories.mp3",
			artist: ["maroon 5", "maroon five"],
			name: ["memories"],
			answer: "Memories by Maroon 5",
		},
		{
			link: "Happier.mp3",
			artist: ["bastille", "marshmello"],
			name: ["happier"],
			answer: "Happier by Bastille (and Marshmello)",
		},
		{
			link: "SomeoneYouLoved.mp3",
			artist: ["lewis capaldi"],
			name: ["someone you loved"],
			answer: "Someone You Loved by Lewis Capaldi",
		},
		{
			link: "StoryOfMyLife.mp3",
			artist: ["one direction"],
			name: ["story of my life"],
			answer: "Story of My Life by One Direction",
		},
		{
			link: "Sunflower.mp3",
			artist: ["post malone", "swae lee"],
			name: [
				"sunflower",
				"spider man",
				"spider man: into the spider verse",
				"spider man into the spider verse",
				"spider man into the spider-verse",
				"spider man into the spider-verse",
				"sunflower (spider-man: into the spider-verse)",
			],
			answer: "Sunflower by Post Malone (and Swae Lee)",
		},
		{
			link: "Ransom.mp3",
			artist: ["lil tecca", "tecca"],
			name: ["ransom"],
			answer: "Ransom by Lil Tecca",
		},
		{
			link: "Shallow.mp3",
			artist: [
				"lady gaga",
				"bradley cooper",
				"lady gaga and bradley cooper",
			],
			name: ["shallow"],
			answer: "Shallow by Lady Gaga",
		},
		{
			link: "Perfect.mp3",
			artist: ["ed sheeran"],
			name: ["perfect"],
			answer: "Perfect by Ed Sheeran",
		},
	],
	"2000s": [
		{
			link: "PokerFace.mp3",
			artist: ["lady gaga"],
			name: ["poker face"],
			answer: "Poker Face by Lady Gaga",
		},
		{
			link: "Umbrella.mp3",
			artist: ["rihanna"],
			name: ["umbrella"],
			answer: "Umbrella by Rihanna",
		},
		{
			link: "SinceYouBeenGone.mp3",
			artist: ["kelly clarkson"],
			name: [
				"since you been gone",
				"since u been gone",
				"since you've been gone",
			],
			answer: "Since U Been Gone by Kelly Clarkson",
		},
		{
			link: "LoseYourself.mp3",
			artist: ["eminem"],
			name: ["lose yourself"],
			answer: "Lose Yourself by Eminem",
		},
		{
			link: "CrazyInLove.mp3",
			artist: ["beyonce"],
			name: ["crazy in love"],
			answer: "Crazy in Love by Beyonce",
		},
		{
			link: "IKissedAGirl.mp3",
			artist: ["katy perry"],
			name: ["i kissed a girl"],
			answer: "I Kissed a Girl by Katy Perry",
		},
		{
			link: "YouBelongWithMe.mp3",
			artist: ["taylor swift"],
			name: ["you belong with me"],
			answer: "You Belong With Me by Taylor Swift",
		},
		{
			link: "MrBrightside.mp3",
			artist: ["the killers", "killers"],
			name: ["mr. brightside", "mr brightside"],
			answer: "",
		},
		{
			link: "Zombie.mp3",
			artist: ["the cranberries", "cranberries"],
			name: ["zombie"],
			answer: "Zombie by The Cranberries",
		},
	],
	"1990s": [
		{
			link: "BabyOneMoreTime.mp3",
			artist: ["britney spears"],
			name: ["baby one more time", "hit me baby one more time"],
			answer: "Baby One More Time by Britney Spears",
		},
		{
			link: "UnbreakMyHeart.mp3",
			artist: ["toni braxton"],
			name: ["unbreak my heart", "un-break my heart"],
			answer: "Un-Break My Heart by Toni Braxton",
		},
		{
			link: "IWantItThatWay.mp3",
			artist: ["backstreet boys"],
			name: ["i want it that way"],
			answer: "I Want It That Way by Backstreet Boys",
		},
		{
			link: "Wonderwall.mp3",
			artist: ["oasis"],
			name: ["wonder wall", "wonderwall"],
			answer: "Wonderwall by Oasis",
		},
		{
			link: "LifeIsAHighway.mp3",
			artist: ["tom cochrane", "rascal flatts"],
			name: ["life is a highway"],
			answer: "Life is a Highway by Rascal Flatts",
		},
	],
};
